name: license-check
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  license-check:
    strategy:
      matrix:
        go-version: ["1.16.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check license
        run: make license-check
