name: ShellCheck
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: shellcheck ./scripts/*